### ISSUE TITLE
[Bug]: Mod version 1.1.0 crashes on launch in 1.19.3, saying it requires 1.19.3

### ISSUE THREAD

**Issue by Abbanon** [Mrbysco/SheepSqueak#1]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

Fabric 0.14.11

### Minecraft version

1.19.3

### Mod version

1.1.0

### Java version

Java 17.0.5 x64 GraalVM build

### Issue Description

![Screenshot_1](https://user-images.githubusercontent.com/37251822/208308158-d6337297-669e-4417-9c1f-4e2fb7f090f1.png)

### Additional Information

https://paste.ee/p/g1mMt

**Comment by Mrbysco** [comment]
Whoops, will upload a fixed version in a bit
